### ISSUE TITLE
Lookahead one frame by inspecting controller input

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#1]
Right now, we do not look at what buttons player 1 is currently pressing. Therefore any 1-frame attacks or blocks (shielding) will take us by surprise. For example, a player could powershield a shine and then get an attack in while we wavedash.

**Comment by altf4** [comment]
Is this "cheating"? Basically, SmashBot will look at your controller to see what buttons you're pressing.. This is something that a player could very well do in person... though it would be difficult due to you being human. I'm not really sure about this.

**Comment by Eppie** [comment]
Imo, yes, this is cheating. However, it would certainly be a neat feature to have. Maybe you could have some config file, and have this default off?

**Comment by altf4** [comment]
Closing this, as I don't think it's something that we want to do. It would also potentially be unreliable for complicated reasons.
