### ISSUE TITLE
Different location of dolphin-emu then default

### ISSUE THREAD

**Issue by gamedeviso** [altf4/SmashBot#103]
Hey, I'm wondering if there's a way to use a version of Dolphin that's not in its typical ./config location. Is it possible to be able to change how SmashBot finds the directory, even just for myself?

**Comment by altf4** [comment]
You can use whatever version of dolphin. Use the -n flag to have SmashBot not automatically start dolphin for you. That lets you run dolphin yourself, then start SmashBot separately. 

Though it will still look in the default config directory... but that ought to be fine.

**Comment by gamedeviso** [comment]
So, if my dolphin config is in /home/name/Documents/testdolph/User/Config, will that be fine? Because SmashBot doesn't seem to be appearing in my build, and I'm not getting any errors

**Comment by altf4** [comment]
Oh, no that won't work... Hmm. That's going to be an issue with libmelee, not smashbot. I could add a feature to specify a custom config directory. But it doesn't exist right now.

Why do you have a custom config directory? Is this something that others are likely to want, too?

**Comment by gamedeviso** [comment]
I have multiple Dolphin builds on Linux, and only one seems to use the default config directory (or else it seems to overwrite it and cause errors). So if I want to use Faster Melee, Faster PM, regular Dolphin 5.0, etc. together, I have to have portable builds that don't use the global user directory.

**Comment by altf4** [comment]
That makes sense. Yea, I'll add a thing in libmelee to do this. Ought to just be a command-line flag.

**Comment by gamedeviso** [comment]
Thanks!

**Comment by altf4** [comment]
I'm going to keep this open as a reminder until I actually commit it. :)

**Comment by clineil** [comment]
hi, is this implemented? i'd love to use smashbot with faster melee. 

should i just make this edit myself?

thx, rad project!

**Comment by altf4** [comment]
Nope, it's not implemented yet. It ought to be straight-forward though in libmelee. Shoot me a PR if you want to tackle it.
