### ISSUE TITLE
Port to wii, possibly via nintendont?

### ISSUE THREAD

**Issue by briantho** [altf4/SmashBot#110]
In regards to getting this running on a real wii, I had an idea. could smashbot run via a custom version/build of nintendont? Just in case you don't know what nintendont is, it a homebrew dol for the wii (and even wii u) which allows gamecube games to run in "wii mode" and has other enhancements, such as wii u support, and virtual memory cards, and usb controllers. Basically, from my understanding it, is a semi-hybrid emulator that converts gamecube syscalls, to wii syscalls on the fly, without ever touching mios. (the part of the wii's ios which runs gamecube games) My idea was if a custom version of nintendont could be created to work with smashbot. I don't know if this would at all be possible, but it is just a thought i had. Here is the link to the project page. https://github.com/FIX94/Nintendont Let me know what you think. Thanks

**Comment by altf4** [comment]
SmashBot runs on Python, so the environment would need to have a Python interpreter. And even then you'd need a whole new I/O mechanism. I haven't even bothered to port to Windows yet, so I'm gonna say that's unlikely. :) But thanks for the tip.

**Comment by briantho** [comment]
Apparently there's now a slippi Nintendont version I JUST found out about. https://www.slippi.gg/downloads

This is supposed to allow for streaming from slippi on the console to the computer. Perhaps it could be reversed so that smashbot still runs on PC, and the players can use a real Wii. I have yet to try slippi nintendont edition, but what do you think?
