### ISSUE TITLE
Having trouble installing the memory watcher based dolphin on a fresh xubuntu install

### ISSUE THREAD

**Issue by briantho** [altf4/SmashBot#112]
I've followed the instructions from [here](https://github.com/altf4/dolphin/tree/memorywatcher-rebased) after cloning the https://github.com/altf4/dolphin/tree/memorywatcher-rebased into a local directory. I also installed the build dependencies from the main version of [dolphin](https://wiki.dolphin-emu.org/index.php?title=Building_Dolphin_on_Linux). Here is what I installed  

> sudo apt install cmake pkg-config git libao-dev libasound2-dev libavcodec-dev libavformat-dev libbluetooth-dev libenet-dev libgtk2.0-dev liblzo2-dev libminiupnpc-dev libopenal-dev libpulse-dev libreadline-dev libsfml-dev libsoil-dev libsoundtouch-dev libswscale-dev libusb-1.0-0-dev libwxbase3.0-dev libwxgtk3.0-dev libxext-dev libxrandr-dev portaudio19-dev zlib1g-dev libudev-dev libevdev-dev "libpolarssl-dev|libmbedtls-dev" libcurl4-openssl-dev libegl1-mesa-dev libpng-dev qtbase5-private-dev

after that I ran cmake and then make and got an error regarding wxwidgets, at 26% when building. I then installed wxwidgets by following the instructions [here](https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries#toc2) , and got waaay further, up to 98%. Now I'm getting

> /home/brian/dolphin3/dolphin-emu/Source/Core/DolphinWX/WxUtils.cpp: In function ‘void WxUtils::SetWindowSizeAndFitToScreen(wxTopLevelWindow*, wxPoint, wxSize, wxSize)’:
/home/brian/dolphin3/dolphin-emu/Source/Core/DolphinWX/WxUtils.cpp:156:34: error: call of overloaded ‘wxDisplay(int)’ is ambiguous
     screen_geometry = wxDisplay(0).GetClientArea();
                                  ^
In file included from /usr/include/wx-3.1-unofficial/wx/event.h:14:0,
                 from /usr/include/wx-3.1-unofficial/wx/app.h:19,
                 from /home/brian/dolphin3/dolphin-emu/Source/Core/DolphinWX/WxUtils.cpp:9:
/usr/include/wx-3.1-unofficial/wx/display.h:141:5: note: candidate: wxDisplay::wxDisplay(const wxDisplay&) <deleted>
     wxDECLARE_NO_COPY_CLASS(wxDisplay);
     ^
In file included from /home/brian/dolphin3/dolphin-emu/Source/Core/DolphinWX/WxUtils.cpp:14:0:
/usr/include/wx-3.1-unofficial/wx/display.h:54:14: note: candidate: wxDisplay::wxDisplay(const wxWindow*)
     explicit wxDisplay(const wxWindow* window);
              ^~~~~~~~~
/usr/include/wx-3.1-unofficial/wx/display.h:50:5: note: candidate: wxDisplay::wxDisplay(unsigned int)
     wxDisplay(unsigned n = 0);
     ^~~~~~~~~
/home/brian/dolphin3/dolphin-emu/Source/Core/DolphinWX/WxUtils.cpp:162:41: error: call of overloaded ‘wxDisplay(int)’ is ambiguous
     default_size.SetDefaults(wxDisplay(0).GetClientArea().GetSize() / 2);
                                         ^
In file included from /usr/include/wx-3.1-unofficial/wx/event.h:14:0,
                 from /usr/include/wx-3.1-unofficial/wx/app.h:19,
                 from /home/brian/dolphin3/dolphin-emu/Source/Core/DolphinWX/WxUtils.cpp:9:
/usr/include/wx-3.1-unofficial/wx/display.h:141:5: note: candidate: wxDisplay::wxDisplay(const wxDisplay&) <deleted>
     wxDECLARE_NO_COPY_CLASS(wxDisplay);
     ^
In file included from /home/brian/dolphin3/dolphin-emu/Source/Core/DolphinWX/WxUtils.cpp:14:0:
/usr/include/wx-3.1-unofficial/wx/display.h:54:14: note: candidate: wxDisplay::wxDisplay(const wxWindow*)
     explicit wxDisplay(const wxWindow* window);
              ^~~~~~~~~
/usr/include/wx-3.1-unofficial/wx/display.h:50:5: note: candidate: wxDisplay::wxDisplay(unsigned int)
     wxDisplay(unsigned n = 0);
     ^~~~~~~~~
Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/build.make:2078: recipe for target 'Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/WxUtils.cpp.o' failed
make[2]: *** [Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/WxUtils.cpp.o] Error 1
CMakeFiles/Makefile2:1029: recipe for target 'Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/all' failed
make[1]: *** [Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

and at that point I'm stuck. Please help me.
I'm going to post the full build log if anyone wants [here](https://pastebin.com/cha9u05F). Again Please let me know what I'm doing wrong. I installed WxWidgets by following [this](https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries#toc2) and running this command. 

> sudo apt-get install libwxbase3.1-0-unofficial \
                 libwxbase3.1-dev \
                 libwxgtk3.1-0-unofficial \
                 libwxgtk3.1-dev \
                 wx3.1-headers \
                 wx-common \
                 libwxgtk-webview3.1-0-unofficial \
                 libwxgtk-webview3.1-dev \
                 libwxgtk-media3.1-0-unofficial \
                 libwxgtk-media3.1-dev \
                 libwxbase3.1-0-unofficial-dbg \
                 libwxgtk3.1-0-unofficial-dbg \
                 libwxgtk-webview3.1-0-unofficial-dbg \
                 libwxgtk-media3.1-0-unofficial-dbg \
                 wx3.1-i18n \
                 wx3.1-examples

Again, I started with  a fresh install of xubuntu 18.04.3. Thanks

**Comment by altf4** [comment]
Looks like some upstream changes conflicted with my build. I resolved the merge conflicts and it seems to be working on my (Ubuntu 18.04) machine.

Use https://github.com/altf4/dolphin (master branch)

**Comment by altf4** [comment]
Latest master branch should work. (No longer uses memory watcher) Give it a try!
