### ISSUE TITLE
Currently ubutu 1.8.0.4 doesn't work with the bot as it it is impossable to build this version of dolphin for it

### ISSUE THREAD

**Issue by kurti256** [altf4/SmashBot#114]
please may you put a (even if short) list of linux/macos that you know work

thank you for reading

**Comment by altf4** [comment]
Looks like some upstream changes conflicted with my build. I resolved the merge conflicts and it seems to be working on my (Ubuntu 18.04) machine.

Use https://github.com/altf4/dolphin (master branch)

**Comment by altf4** [comment]
Latest master branch "should" work! Give it a try.
