### ISSUE TITLE
Need Assistance

### ISSUE THREAD

**Issue by Andrew-Pynch** [altf4/SmashBot#115]
Hello friend.

Firstly, let me thank you for all the hard work you have put into this project. I need your help with a couple of things if you have a moment...

1. I cannot get your custom fork of dolphin to work :-(. Can I still use meleelib to read from arbitrary dolphin versions memory?
2. There doesn't appear to be any documentation for the meleelib (unless I am a complete idiot and am missing something obvious.) How could I only read:
- Each players health at a given time?
- Each players stock count at a given time?
3. How can I use meleelib to pipe in arbitrary inputs? I love that you hardcoded lots of common strategies/tactics, but I would like to see if it is possible for an agent to learn such behaviors without having an explicit ability to "call" them.

Again thanks for your hard work! If you have time please answer these questions as it would be a massive help on my current smashbot!

~Cheers

**Comment by altf4** [comment]
Hey no prob!

1) Yea, that branch doesn't work. It's broke. But good news! I'm working on making this all work with Slippi. So it'll be way easier to use here real soon. I'm coding up some networking code for Slippi right now as we speak. But keep an eye on this PR: https://github.com/project-slippi/Ishiiruka/pull/35

Once that's merged in, you'll be able to use libmelee with upstream slippi Ishiiruka. (The ones ppl usually use for netplay)

2) You're interested in libmelee. It's in a separate repo: https://github.com/altf4/libmelee/
libmelee is basically all the smashbot stuff that is plumbing, and not actually "smashbot".

3) libmelee ought to have some good examples for pressing buttons.

**Comment by Andrew-Pynch** [comment]
That is exciting to hear! Let me know if you need help getting things written https://github.com/project-slippi/Ishiiruka/pull/35 (although it looks like they are almost ready to merge this?)

Thank you for your advice! Looking forward to sharing some exciting results :D

**Comment by Andrew-Pynch** [comment]
Forgot to close this issue. You definitely helped out here! :-) 

Again, let me know if you need any help on the Slippi port. I would love to contribute since this would be an extremely useful tool for the work I am doing right now.

**Comment by Andrew-Pynch** [comment]
Actually have to reopen this issue. When I attempted to use libmelee with dolphin 5.0 I got the same unknown pointer crash referenced here. 
https://github.com/altf4/libmelee/issues/13

In that issue you recommend installing your fork of dolphin. 
https://github.com/altf4/dolphin/tree/memorywatcher-rebased
Unfortunately, I cannot build this fork from the source and receive the following error when running make.
```
fatal error: xlocale.h: No such file or directory
         #include <xlocale.h>
```
When searching for this error I found this issue which states that xlocale.h is no longer available. 
https://github.com/meta-toolkit/meta/issues/195

libmelee appears to be working great. Would love if you have any insight on how to resolve this pointer error while we are waiting for your fork of slippi to get merged into master.

**Comment by altf4** [comment]
You sort of caught me halfway between working builds, unfortunately. I think that "memorywatcher-rebased" branch should work, but it's so old that it doesn't build anymore with dolphin's build setup, apparently. So I tried rebase-ing again, but I think it's just irreparably busted. That branch uses MemoryWatcher in dolphin, which is a really kludgey way of doing it.

The new mechanism is going to use Slippi. I'm currently working on that. If you want a speak-peek, you can use this branch of libmelee:

https://github.com/altf4/libmelee/tree/slipstream
and this branch of Ishiiruka (dolphin)
https://github.com/altf4/Ishiiruka/tree/wintest

But this is all in a state of high flux as I get it working properly. Honestly, I don't want to bother fixing up that old dolphin branch because it'll be a huge pain and will be replaced by Slippi soon here anyway

**Comment by Andrew-Pynch** [comment]
Hey thanks for getting back to me so quickly. I tried to build your branch of slippi but am getting stuck on the ```sudo make install```. My terminal output is

```
CMake Error at Externals/cubeb/cmake_install.cmake:49 (file):
  file INSTALL cannot find
  "/home/andrew/Downloads/Ishiiruka-wintest/include".
```
any ideas? Sorry to bother again.

**Comment by altf4** [comment]
I haven't tried installing, if it builds, just run it in place

**Comment by Andrew-Pynch** [comment]
That worked! (sorry for dumb questions, still a little new to the c++ development world)

Now I am back to getting an Unknown Pointer error. Is there a more recent branch you have been working off of?
![image](https://user-images.githubusercontent.com/43330642/82781368-79e4f400-9e0e-11ea-9d25-47290a43dbc8.png)

**Comment by Andrew-Pynch** [comment]
Still getting after install the canberra-gtk-module
![image](https://user-images.githubusercontent.com/43330642/82781648-33dc6000-9e0f-11ea-8921-b6ef9fc36511.png)

**Comment by Andrew-Pynch** [comment]
Not sure if this is useful information but I was able to host a netplay server and run the latest version of the slippi libmelee example. Seems to get stuck printing this 
![image](https://user-images.githubusercontent.com/43330642/82822272-5b0c4f00-9e5a-11ea-89b4-a210717a584b.png)


Is the only way to use this new version of slipii libmelee to use a hacked wii?

**Comment by altf4** [comment]
That's the Slippi version of dolphin and the game, so you have to apply the right cheats and enable them. These are the latest FM codes:

https://raw.githubusercontent.com/project-slippi/slippi-ssbm-asm/master/Output/Netplay/GALE01r2.ini

The new libmelee is being designed to read the Slippi data over the network. So it'll work on either a hacked Wii console or a Slippi dolphin setup (which is in development still) Also reading .slp files too, I suppose. But I haven't done that yet.

**Comment by altf4** [comment]
fwiw, those "keepalive" messages are sent by the console when no Slippi match data is being sent. So if you're seeing that, it means libmelee has successfully connected to the console. :)

**Comment by Andrew-Pynch** [comment]
Applied those codes to no avail. I reached out to the author of Slippi to see if he has any input. Thank you for all your help!
