### ISSUE TITLE
Stale Bot (No input)

### ISSUE THREAD

**Issue by OoLunar** [altf4/SmashBot#116]
Hello!
I'm attempting SmashBot on Ubuntu 20.04, with the Dolphin Emu from [the description](https://github.com/altf4/dolphin/). I cloned and built the dolphin repo, everything went fine other than 20+ warnings about `warning: type qualifiers ignored on function return type`, variable shadowing, etc. Then I cloned this repo, ran `smashbot.py`, and started playing. According to other issues, output is supposed to occur, and yet none is shown. When I run SmashBot in debug mode, a log file is created with the contents of
```
Frame,Opponent x,Opponent y,AI x,AI y,Opponent Facing,AI Facing,Opponent Action,AI Action,Opponent Action Frame,AI Action Frame,Opponent Jumps Left,AI Jumps Left,Opponent Stock,AI Stock,Opponent Percent,AI Percent,Buttons Pressed,Notes,Frame Process Time
```
I believe I'm using the correct version of Melee, American flag and 1.36GB file size. I enabled the Netplay Community and Frozen stages Gecko Cheats, and yet... Player 2 does nothing on the player selection screen. When I force set SmashBots character to Fox (Through changing P2 to CPU, setting CPU's character, then setting P2 back to human) SmashBot only shields. This goes on forever, numerous shield breaks, perfect break shield combo dummy. In Dolphin's controller config, everything _seems_ correct, except for the input device. The devices available are my keyboard, my GC controller, `Pipe/0/Bot2` (Default) and `Pipe/0/Bot1`. Both bots repeat the shield breaking action, with no known difference. Any clues on what to do?

**Comment by altf4** [comment]
You sort of caught me halfway between working builds, unfortunately. I think that "memorywatcher-rebased" branch should work, but it's so old that it doesn't build anymore with dolphin's build setup, apparently. So I tried rebase-ing again, but I think it's just irreparably busted. That branch uses MemoryWatcher in dolphin, which is a really kludgey way of doing it.

The new mechanism is going to use Slippi. I'm currently working on that.

**Comment by OoLunar** [comment]
Is there a commit or release I can use that you know for sure will work?

**Comment by altf4** [comment]
Hey @OoLunar The latest Master build should work! Give it a try.

**Comment by OoLunar** [comment]
Wonderful! I'll give it a test when I get home! Thank you very much!

**Comment by OoLunar** [comment]
Ubuntu can't install `pywin32`, so I switched to Windows. It seems I've encountered a number of bugs... I'll list them out one by one

1. With the command `python3 .\smashbot.py -e "C:/Users/Lunar/Documents/Dolphin Emulator/"` I get the response
```
Traceback (most recent call last):
  File ".\smashbot.py", line 99, in <module>
    console.run()
  File "C:\Users\Lunar\Downloads\SmashBot\melee\console.py", line 113, in run
    self.process = subprocess.Popen(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
2. By doing `python3 .\smashbot.py -e "C:\Users\Lunar\Documents\Dolphin Emulator\"` I get the response
```
usage: smashbot.py [-h] [--port PORT] [--opponent OPPONENT] [--bot BOT] [--debug] [--difficulty DIFFICULTY] [--nodolphin] [--dolphinexecutable DOLPHINEXECUTABLE] [--configdir CONFIGDIR] [--address ADDRESS]
smashbot.py: error: argument --dolphinexecutable/-e: C:\Users\Lunar\Documents\Dolphin Emulator" is not a directory
```
*Note, I can directly copy and paste the output dir into the File Manager, and navigated into the folder without issue*
3. Upon starting SmashBot, it looked for `<Dolphin Dir>/User/Config/GCPadNew.ini` Instead of `<Dolphin Dir>/Config/GCPadNew.ini`. A simple copy and paste of files fixed this.

**Comment by OoLunar** [comment]
I can see that you just made a new commit. Let me double check to see if the bugs are still present

**Comment by OoLunar** [comment]
I can confirm that all problems are still present. Not sure what I can do

**Comment by altf4** [comment]
oh, you can just ignore the pywin32 dependency for Linux/OSX. I'll have to make that optional somehow.

The error is `C:\Users\Lunar\Documents\Dolphin Emulator"` is not a directory. Is that true? Looks like there's an odd trailing quote? Something weird with your path?

**Comment by OoLunar** [comment]
No... Nothing odd in my path, nothing weird going on at all. I'll make another attempt on Ubuntu without the winpy dependency

**Comment by altf4** [comment]
Oh, it's probably because you're escaping the quote. Paths on Windows is dumb.

`python3 .\smashbot.py -e "C:\Users\Lunar\Documents\Dolphin Emulator\"`

That trailing quote at the end is being escaped and is part of the path.

**Comment by OoLunar** [comment]
Ah... I should've seen that! As for Ubuntu, I get the error:
```
Traceback (most recent call last):
  File "smashbot.py", line 99, in <module>
    console.run()
  File "/home/lunar/Code/SmashBot/melee/console.py", line 101, in run
    command = [self.dolphin_executable_path + exe_name]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by altf4** [comment]
oh blah. That's a good bug :) dolphin path is None. I can fix that.

As a quick workaround, specify the Dolphin path with -e

**Comment by OoLunar** [comment]
Understood!

**Comment by altf4** [comment]
If you don't supply a -e flag, SmashBot assumes you're using the "installed" version of Dolphin. In case that wasn't clear... which it might not be

**Comment by OoLunar** [comment]
Ironically enough, I am using the installed version of Dolphin with Ubuntu, but the portable version with Windows

**Comment by OoLunar** [comment]
```
python3 smashbot.py -e "/home/lunar/.config/dolphin-emu"
Traceback (most recent call last):
  File "smashbot.py", line 65, in <module>
    console = melee.console.Console(ai_port=args.port,
  File "/home/lunar/Code/SmashBot/melee/console.py", line 58, in __init__
    self.setup_dolphin_controller(ai_port)
  File "/home/lunar/Code/SmashBot/melee/console.py", line 181, in setup_dolphin_controller
    config.set("Core", 'SIDevice'+str(port-1), controllertype.value)
  File "/usr/lib/python3.8/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib/python3.8/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Core'
```
I also had to create the `User/Config/GCPadNew.ini` by copying and pasting. I found config file at `/home/lunar/.config/dolphin-emu/GCPadNew.ini`

**Comment by altf4** [comment]
That's part of using Ishiiruka, maybe it's not documented in their build steps? You have to copy the `Overwrite` directory into the place where `Dolphin.exe` is

**Comment by altf4** [comment]
Oh, that's for an installed copy, nvm. Hmm, I think that part is broken right now :/ I'll fix that. In the meantime, try using a local non-installed version

**Comment by OoLunar** [comment]
Ah, I see. I'm not using the Ishiiruka build of Dolphin. Pardon me for being ignorant

**Comment by altf4** [comment]
Yea, the Readme has instructions. Use the version here (until the changes are mainlined) https://github.com/altf4/Ishiiruka/tree/beta

**Comment by OoLunar** [comment]
I apologize for the very late response. Family had spilled water onto my computer, breaking it. Thankfully, I had an old one in storage, and I'm currently getting Smashbot to work on it. I have successfully compiled Ishiiruka, and got Smashbot working with only two issues remaining. Hooray!

Looking at the setup, you want the Gecko codes `Faster Melee Netplay Settings`,  `Normal Lag Reduction`, and `Slippi Recording` enabled. After downloading the Gecko codes from the [link you provided](https://github.com/project-slippi/slippi-ssbm-asm/blob/master/Output/Netplay/GALE01r2.ini), I enabled the `Normal Lag Reduction` and `Slippi Recording`, however was unable to find `Faster Melee Netplay Settings`. Additionally, my GC controller was unable to use it's `Main stick` and `C stick` to control the menu like I could previously (tested on latest Beta Dolphin build, works as expected. Completely fails on Ishiiruka). As for the `Faster Melee Netplay Settings` Gecko Code, I tested to see if it was on the original `GALE01r2.ini` config, which it wasn't. Out of desperation to get my control sticks working again, along with testing to see if the `Netplay Community Settings` would work in place of the `Faster Melee Netplay Settings`. No difference, although I didn't expect it to work in the first place.

**Comment by OoLunar** [comment]
Also, upon running the Smashbot script, here's the following output:
```python3
python .\smashbot.py -e "C:/Users/lunar/Code/Ishiiruka-r18/Binary/x64/"
Connecting to console...
ERROR: Failed to connect to the console.
        If you're trying to autodiscover, local firewall settings can get in the way. Try specifying the address manually.```
While I believe I completely allowed Python3/SmashBot on Windows Firewall, I'm rather in doubt. I'll attempt to try to disable the Firewall, and see where that gets me.

**Comment by OoLunar** [comment]
Firewall doesn't seem to be the issue. Can't find the Faster Melee Gecko Code anywhere

**Comment by altf4** [comment]
Try these codes: https://github.com/altf4/slippi-ssbm-asm/blob/master/Output/Netplay/GALE01r2.ini

It includes menu state info that's not in mainline right now

**Comment by altf4** [comment]
As for connecting, try specifying the local address:

`python .\smashbot.py -e "C:/Users/lunar/Code/Ishiiruka-r18/Binary/x64/" -a 127.0.0.1`

**Comment by OoLunar** [comment]
Found the `Faster Melee Netplay Settings` Gecko code, however when the `Lag Reduction` Gecko code is used, it causes the game to not even load... Ironic considering it's name lmao. I'm rather confused though because this didn't happen before, but it did now (even though it's the same Gecko code from the one linked in the `Read.me`. The only difference is that I used the latest Ishiiruka commit instead of the latest release (which I did before) in attempt to get Smashbot working. I'm going to attempt to use both latest commit and latest release to see if it makes a difference (Not both at once obviously).

As for specifying the Smashbot address: No difference.

**Comment by OoLunar** [comment]
I compiled both the latest Git and the latest Release of Ishiiruka, replaced the `GALE01r2.ini` in `Ishiiruk-{Git | Release}\Binary\x64\Sys\GameSettings` with the one you linked. Ran Ishiiruka and Smashbot as administrator to see if it was a port permission issue. I couldn't get Smashbot to connect. I ran Smashbot in debug mode, and a `csv` file was created with no debug output inside. I have no other ideas of what to do. If there's anything else I can provide, please let me know.

I apologize if I'm being a nuisance.

**Comment by altf4** [comment]
"the latest Release of Ishiiruka" won't work. You have to use this branch: https://github.com/altf4/Ishiiruka/tree/beta

**Comment by OoLunar** [comment]
That was the branch I was using. By "latest release" I was referencing https://github.com/altf4/Ishiiruka/releases/tag/r18

**Comment by altf4** [comment]
r18 won't work either. You have to use my "beta" branch that I linked to.

**Comment by OoLunar** [comment]
I've wasted so much of our time because of my ignorance. I deeply apologize. I've compiled the beta branch, and attempted to launch Smashbot. Dolphin now recognized Smashbot as a device, as shown: 
![image](https://user-images.githubusercontent.com/46751150/86293589-8b14e380-bbb8-11ea-87f1-481506acd6d0.png)
However when I launch Melee, Dolphin immediately crashes. I've tried again without Smashbot or Gecko codes, and it keeps crashing. I'm now making an attempt at finding the log files to see what went wrong

**Comment by OoLunar** [comment]
Here's the log: https://hastebin.com/raw/ojamimidel

**Comment by underscoreglook** [comment]
To piggyback on this, on my machine (Windows), it's failing in get_dolphin_pipes_path. I've searched on my computer for "\\.\pipe\slippibot2" but I can't seem to find it. Is there a setup step I missed to set this pipe up?

**Comment by altf4** [comment]
Named pipes on Windows don't exist on the real filesystem. They're in a virtual location `\.\pipe\` So you're not going to be able to "find it". 

If libmelee is unable to find `\.\pipe\slippibot2` it's because you're not using the right Ishiiruka.

**Comment by underscoreglook** [comment]
Oh it defaults to the slippi branch, my bad. Recompiling with beta branch, thanks!

**Comment by altf4** [comment]
FYI: I just updated the Readme on both SmashBot and Libmelee to use the new Ishiiruka code. It uses the Ishiiruka spectator feature, so definitely give that a try.

**Comment by underscoreglook** [comment]
Thanks. When I throw fox off stage, he lasers instead of recovering; is that expected?

**Comment by altf4** [comment]
Are you running the libmelee example.py? Or SmashBot?

**Comment by underscoreglook** [comment]
smashbot.py, not example.py

**Comment by altf4** [comment]
Look at the controller config for the bot. Does it look like:
![image](https://user-images.githubusercontent.com/609563/86555862-7dd45d80-bf06-11ea-8d7e-e4d8007f66a3.png)

Ive seen the `radius` get messed up before, for sure.

**Comment by underscoreglook** [comment]
All of the numbers were zero somehow, and Dolphin crashes when exiting the controller screen. Fortunately, editing GCPadNew.ini worked, and now it's kicking my butt.

Thanks for the help!
