### ISSUE TITLE
Ledgehop -> Counter

### ISSUE THREAD

**Issue by atvo912** [altf4/SmashBot#117]
Smashbot falls for ledgehop -> counter a majority of the time, shining early and activating the counter. Smashbot has no problem dealing with double jump -> counter mid-stage, though, only from ledgehops for some reason.

**Comment by altf4** [comment]
Note to future self: This SEEMS to be because libmelee treats counter as a "roll". Which is incorrect. It's really a new kind of hitbox that needs to be accounted for

**Comment by altf4** [comment]
A quick hack might be to keep counter as a "ROLL" and make it "invincible" during the counter frames. (So it won't try to attack in that window). 

Though that's a big ugly.

**Comment by altf4** [comment]
Fixed this by adding in the invulnerability frames for counter
