### ISSUE TITLE
Smashbot issues on windows 10

### ISSUE THREAD

**Issue by briantho** [altf4/SmashBot#122]
I finally have Ishiiruka built correctly. (at least i think) There were some issues in visual studio 2019, just warnings. Here is the warrning just in case you wanted to see it.  there are several of these

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4067	unexpected tokens following preprocessor directive - expected a newline	open-vcdiff	c:\users\brian thompson\downloads\ishiiruka - copy - copy\externals\open-vcdiff\src\google\codetablewriter_interface.h	25	
```
anyway, after building the version from [here](https://github.com/altf4/Ishiiruka/tree/gamma) I am trying to run smashbot. I put the compiled binary directory under the smashbot directory, and then when running smashbot.py with the -e option and pointing it to the Binary/x64 directory, Dolphin launches, but smashbot never connects to "the console" I saw in another post to disable the firewall and use the  -a "127.0.0.1"

This got me to `Connecting to console...
Connected
Traceback (most recent call last):
  File "C:\Users\Brian Thompson\Downloads\SmashBot\smashbot.py", line 110, in <module>
    controller_one.connect()
  File "C:\Program Files\Python38\lib\site-packages\melee\controller.py", line 99, in connect
    self.pipe = win32file.CreateFile(
NameError: name 'win32file' is not defined`

Also when running the custom build of dolphin, with melee it gives me this screen.  
![smashbot problem](https://user-images.githubusercontent.com/3977205/88430899-76da9580-cdb6-11ea-8b68-1a260c664a5b.png)

Is that screen normal? What do i do? A or start does nothing. If I press b on the gamecube controller i get a panic handler screen. I also made sure to replace the GALE01r2.ini file with this [one](https://github.com/altf4/slippi-ssbm-asm/blob/master/Output/Netplay/GALE01r2.ini), but it's still not working. Please help me. Thanks

Also, here is a screenshot of the controller for player 2 aka smashbot. Seems to be ok. 
![smashbot problem 2](https://user-images.githubusercontent.com/3977205/88431064-d46ee200-cdb6-11ea-968c-844b651c288e.png)

**Comment by altf4** [comment]
The error `NameError: name 'win32file' is not defined` is because I have to figure out conditional dependencies. I have an Issue for it already. https://github.com/altf4/libmelee/issues/42

In the meantime you can just install it yourself with:
`pip install pywin32`

Let me look into the other issue for you.

**Comment by briantho** [comment]
WOw, that was fast.  I just tried running "pip install pywin32" but it's still got the same error

Here is the full command as well as the output

`C:\Users\Brian Thompson\Downloads\SmashBot>smashbot.py -e "Binary\x64" -a "127.0.0.1"
Connecting to console...
Connected
Traceback (most recent call last):
  File "C:\Users\Brian Thompson\Downloads\SmashBot\smashbot.py", line 110, in <module>
    controller_one.connect()
  File "C:\Program Files\Python38\lib\site-packages\melee\controller.py", line 99, in connect
    self.pipe = win32file.CreateFile(
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')`

**Comment by briantho** [comment]
is there some other missing dependency? If i omit the -a flag smashbot says "connecting to console..." but nothing ever happens

**Comment by altf4** [comment]
Actually, that's a different error. :) 

Looks like it's trying to find the named pipe for the controller but it's not there. (there ought to be a better error for that case. I'll make a note of that) Are you super sure you're running the gamma branch? It should have made named pipes for you...

**Comment by altf4** [comment]
Oh, try making sure that you have a Slippi device in memory card slot B.

![image](https://user-images.githubusercontent.com/609563/88432649-7a1f5280-cdb1-11ea-89ef-6396a467c03b.png)

**Comment by briantho** [comment]
It is the latest gamma branch, also, now i have Slippi selected in slot B for the memory cards. Also should there really be nothing in memory card slot a? Also why don't i have a slippi replay settings option under the gamecube tab under my windows build? Is that something new?

**Comment by altf4** [comment]
Do you have a `Sys/GameFiles` directory? Adjacent to Dolphin.exe

**Comment by altf4** [comment]
Also make sure your ISO is valid by right clicking melee in Dolphin and going to Properties->Info and checking that the revision of Melee is #2.

Compute the MD5 hash of the ISO by clicking the Compute button and make sure it matches 0e63d4223b01d9aba596259dc155a174

**Comment by briantho** [comment]
There is a SYS/GameSettings Directory, but not a GameFiles Directory. 
Also, at first i was using the wrong version of melee, now I am using the correct one.  (yeah i have 3 versions of melee. 1 is 1.0, one is 1.2 and one is pal. I was using 1.0) Now I've got that corrected and confirmed with a a md5 hash of 0e63d4223b01d9aba596259dc155a174 
but still get the same error with smashbot, and the same weird screenshot.

**Comment by briantho** [comment]
Here is a screenshot of my directory structure for dolphin.
![smashbot](https://user-images.githubusercontent.com/3977205/88436569-c7a3bb80-cdc1-11ea-8ea8-355c28d2af2b.png)
![smashbot 2](https://user-images.githubusercontent.com/3977205/88436590-cffbf680-cdc1-11ea-9ba0-721187a90f73.png)

Also, I created a portable.txt file so it would not pull settings from my main Dolphin build

**Comment by altf4** [comment]
Looks like you need to copy the `Sys` folder over. This should have happened automatically for you in the build process. Not sure why it didn't:

https://github.com/altf4/Ishiiruka/tree/gamma/Data

**Comment by briantho** [comment]
ok, so I decided to sort of start over and clone the gamma build once more. after loading visual studio 2019, and building dolphin, i am getting this error. 

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: struct version::Version_data __cdecl version::Semver200_parser::parse(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?parse@Semver200_parser@version@@QEBA?AUVersion_data@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Dolphin	C:\Users\Brian Thompson\Downloads\temp\Ishiiruka \Source\Core\DolphinWX\Core.lib(EXI_DeviceSlippi.obj)	1	
`

**Comment by briantho** [comment]
So, I am still getting this error. Any luck figuring out what the problem is or what I am doing wrong? Are you able to successfully build on windows? Here is step by step what i am doing, along with the errors, maybe this will help. It is possible it's something I am doing wrong, but I am not sure. 

first, I git clone to my downloads directory
git clone --single-branch -b gamma https://github.com/altf4/Ishiiruka.git

After that i open up Ishiiruka/Source/Dolphin.sln

Visual studio asks me to upgrade the platform toolset to v142. I say no upgrade. it also asks what sdk version to use. I select 10.0.17763.0
![2020-07-27 13_13_32-Dolphin - Microsoft Visual Studio](https://user-images.githubusercontent.com/3977205/88581899-142e0780-d00b-11ea-8455-2e792e22e173.png)


I then make sure to select release > x64 up at the top tab
Then I start building dolphin. 

Here is a screenshot of the warrnings, and 1 error. 
![2020-07-27 13_20_59-Dolphin](https://user-images.githubusercontent.com/3977205/88582521-12b10f00-d00c-11ea-97e7-5e44577bcda4.png)

I then go and right click the externals directory and say rebuild as per [this ](https://github.com/altf4/Ishiiruka/tree/gamma)

> If you have trouble with some .lib files missing, right click the Externals directory and click rebuild.

This provides me with the previous screenshot minus the "cannot open input file" error 


After that I right click the dolphin directory in the right hand solution explorer and say "build"

This gives me this error

![2020-07-27 13_37_30-Dolphin - Microsoft Visual Studio](https://user-images.githubusercontent.com/3977205/88584125-6e7c9780-d00e-11ea-8115-472b6f13be7a.png)


Also, i wanted to ask have you built this successfully under windows 10. If so do you have a pre-compiled binary you could just share. This would be appreciated. If not could you please let me know what/if i am doing anything wrong. Thanks

**Comment by altf4** [comment]
That's an issue that happens when building upstream Ishiiruka on Windows too. Some Visual Studio idiocy. 

Just try rebuilding and closing and reopening VS. Yes, it's that stupid

**Comment by briantho** [comment]
WTF, really!!! never would have guessed that one. Now it's built. Yeah. Now running smashbot, and it's sort of working. p2 selects fox, I select kirby as a test. Then the stage loads, but smashbot is stuck guarding, and not moving. Here is the output from the smashbot console. 

Connecting to console...
Connected
Traceback (most recent call last):
  File "C:\Users\Brian Thompson\Downloads\SmashBot\smashbot.py", line 146, in <module>
    agent1.act(gamestate)
  File "C:\Users\Brian Thompson\Downloads\SmashBot\esagent.py", line 29, in act
    self.strategy.step(gamestate,
  File "C:\Users\Brian Thompson\Downloads\SmashBot\Strategies\bait.py", line 78, in step
    if Infinite.caninfinite(smashbot_state, opponent_state, gamestate, self.framedata, self.difficulty):
  File "C:\Users\Brian Thompson\Downloads\SmashBot\Tactics\infinite.py", line 68, in caninfinite
    endposition = opponent_state.x + framedata.slide_distance(opponent_state, opponent_state.speed_x_attack, framesleft)
  File "C:\Program Files\Python38\lib\site-packages\melee\framedata.py", line 852, in slide_distance
    normalfriction = self.characterdata[character_state.character]["Friction"]
KeyError: <Character.KIRBY: 4>

Thanks for your great support. I really appreciate it.

**Comment by altf4** [comment]
Kirby is not supported yet. Pick a different character

**Comment by briantho** [comment]
ah ok got it, which characters are supported. Is there a list, of who is and who is not?

**Comment by altf4** [comment]
Current list: https://github.com/altf4/SmashBot/blob/master/smashbot.py#L113

**Comment by briantho** [comment]
ah ok, got it. now it's working with samus. Are you planning to add more characters? That would be great if so.  Still so far it's working as expected. Pretty impressive.

**Comment by briantho** [comment]
Also why not have a list of supported characters on the readme?

**Comment by altf4** [comment]
Yea, I plan on supporting the whole cast eventually. It's not a simple process, is all. Basically every character has some weird and unique mechanic or move that breaks everything. And there's other priorities first before Kirby :)

**Comment by briantho** [comment]
LOL, Ok, no problem. Looks like the your going by tier which is probably a good idea. I'm just glad it's working now. Thanks again, and I await the day where every character is playable. No rush.
