### ISSUE TITLE
Smashbot launch issue in Win10

### ISSUE THREAD

**Issue by Youssef-Azijni** [altf4/SmashBot#139]
Whenever I run 
`$ py smashbot.py "C:\Dolphin Emu\Slippi.gg" --debug`

I get this error 
`Traceback (most recent call last):
  File "smashbot.py", line 11, in <module>
    from esagent import ESAgent
ModuleNotFoundError: No module named 'esagent'`

I have been unable to find the 'esagent' module on pip,
could anybody help me locate it?

**Comment by altf4** [comment]
Sounds like you only copied `smashbot,py` and not the rest of the code.
