### ISSUE TITLE
configparser.py SyntaxError

### ISSUE THREAD

**Issue by Drflash55** [altf4/SmashBot#140]
Trying to get this working on Windows 10 with the latest version of Slippi.

Had to move all the dependencies to the SmashBot folder along with finding configparser.py inside Python3.8's Lib folder, but upon trying to run it, I'm greeted with this error:

```python
dir>smashbot.py -e "G:\Preston's Stuff\Drflash55's Games\FM-Slippi"
Traceback (most recent call last):
  File "dir\smashbot.py", line 7, in <module>
    import melee
  File "dir\melee\__init__.py", line 5, in <module>
    from melee.console import *
  File "dir\melee\console.py", line 12, in <module>
    import configparser
  File "dir\melee\configparser.py", line 435
    option, section, rawval, var) from None
                                     ^
SyntaxError: invalid syntax
```

I'm not sure if I'm doing something wrong, because everything should be there and accounted for.

EDIT: This is how the folder currently looks.
![image](https://user-images.githubusercontent.com/13694448/99282910-4fdf1e00-2802-11eb-88b6-22003523f62b.png)

**Comment by altf4** [comment]
Was there something wrong with using the version of libmelee on pip?

**Comment by Drflash55** [comment]
Well I had figured it was a common issue that if you try running smashbot.py inside the folder, it tries to look for dependancies inside the folder itself, instead of where it's kept inside "dir\Python38\Lib\site-packages".

That's why I ended up moving everything into the folder so that it could try running it properly.
But I can't find out what the issue is.

**Comment by altf4** [comment]
Looks like you're making this a lot more complicated than it needs to be :) You can just `pip install melee`. And then run smashbot.py. Don't copy anything into the smashbot folder

**Comment by Drflash55** [comment]
I had already tried that previously. But when I did, it couldn't find anything that it had installed with pip.

```python
Traceback (most recent call last):
  File "dir\FM-Slippi\SmashBot\smashbot.py", line 7, in <module>
    import melee
ImportError: No module named melee
```

**Comment by altf4** [comment]
Then you've got a python issue. Perhaps the pip you're running is for a different python version. That's an easy mistake to make.

**Comment by Drflash55** [comment]
I did end up updating pip to the most recent one today since it mentioned it was outdated, but I am running on Python 3.8 currently at the moment.

Perhaps I may have to get Python 3.9, which is the current version as of today?

**Comment by altf4** [comment]
python 3.8.5 works fine on my windows 10 machine. I haven't tried 3.9.x but I bet it'd be fine. 

The issue isn't likely the python _version_, but the possibility that you have more than one python version installed. I'd go into the programs options and make sure there's only one python version installed.

**Comment by Drflash55** [comment]
Yes. You would be correct on that. I have Python 3.8 located in Program Files, and there also exists Python 2.7 which is only used for another program unrelated to this (SmoothVideo Project 4, which is mandatory AFAIK), and that is located on the root directory of C:\.

It's not located in Program Files, but it is part of the "PATH" of "System variables".

I could try completely removing Python 2.7 and see if it's still possible to run SVP4 on Python 3.8 instead.

**Comment by altf4** [comment]
What's happening here is that you're installing libmelee on the wrong python version. You can specify by saying `python3 -m pip install melee` Or whatever the correct python program is. Run `python3 --version` to see.

**Comment by Drflash55** [comment]
Huh, strange.

I actually just tried running that, and CMD returns nothing. Guess I'll have to figure out this issue then.

**Comment by Drflash55** [comment]
Seeing as I'm having issues with running `python3` in CMD, I'm gonna do a clean installation of Python 3.9 with 3.8 & 2.7 removed to see if this ends up fixing my issue.

I'll have to reinstall libmelee once I'm done.

**Comment by Drflash55** [comment]
Alright, so I was able to fix my issue.

I did a clean install of Python 3.9, reinstalled libmelee to the user directory (AppData) and added it to the PATH.

Now when I run smashbot.py, everything works as it should.
