### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by BlaineHalvorson** [altf4/SmashBot#142]
![Screenshot 2021-04-18 183113](https://user-images.githubusercontent.com/39428665/115162940-5ead5380-a074-11eb-978a-bb2ab545dac7.png)

![Screenshot 2021-04-18 183506](https://user-images.githubusercontent.com/39428665/115163027-d54a5100-a074-11eb-9a22-f324fc25c2d8.png)

Whenever I try to run the smashbot.py -e [path to slippi] command I always get an error saying no module named melee was found. I have already done the steps outlined in the README and installed melee with pip.

**Comment by altf4** [comment]
Looks like you might be using two different versions of python. The pip you're using is for a different python than smashbot is using.

**Comment by BlaineHalvorson** [comment]
How exactly do I fix that? What python does smashbot use?

**Comment by altf4** [comment]
Try explicitly running `python smashbot.py -e PATH` instead. And `python -m pip install melee`

**Comment by BlaineHalvorson** [comment]
That seemed to work but now it says Connecting to console, and Connected, opens slippi but when I start melee the bot doesn't seem to be on. Nothing happens on port 2. (Also side note all the characters locked ever since I used the GALE0r2.ini file in the README)

**Comment by altf4** [comment]
I seem to have linked to the wrong gecko codes in the readme. I'll fix that tonight. Here's the right one: https://github.com/altf4/slippi-ssbm-asm/blob/libmelee/Output/Netplay/GALE01r2.ini Try that

**Comment by BlaineHalvorson** [comment]
That fixed it, it's running now but the bot can't wavedash lol I can make that a separate issues if you want though?

**Comment by altf4** [comment]
Disable the "Enable delay to all in-game screens" gecko code.
