### ISSUE TITLE
Any plans to add human-like limits (e.g. reaction time)?

### ISSUE THREAD

**Issue by chausies** [altf4/SmashBot#143]
There's nothing wrong with making Smashbot super consistent and super smart, but it'd be cool if it didn't overtly dip into super human.

For example, in Starcraft AI competitions, they often limit the AI's APM to something more human level.

I think it would be dope if smashbot, at the very least, added a 6-frame "reaction time" delay to what it sees, corresponding to the fastest reaction time a human's ever had (0.1 seconds). This would take away degenerate options like spot-dodging every grab, and would probably even force the bot to make reads.

You might also consider limiting APM to maybe something like 300 (which is over [what Hax achieves](https://redd.it/1upzsp) apparently).

Are there any plans to impose these human-like limits? 

Cheers! Keep up the amazing work!

**Comment by altf4** [comment]
Nope. That's not what SmashBot is for. SmashBot is meant to be a playable TAS.
