### ISSUE TITLE
smashbot doing something very weird. 0kb log. see video. 

### ISSUE THREAD

**Issue by briantho** [altf4/SmashBot#147]
not sure what;s happening. smashbot used to work perfectly. now it's doing something very strange. it approches the player then immediately backs up, then repeats this process several times till hitting the player. see the attached video. i have no explanation for what changed. logs are 0kb. something changed, but what? i've tried cloning the project again, updating libmelle, and updated and reinstalled python. running windows 11 22h2, and python 3.10.8.

https://user-images.githubusercontent.com/3977205/198163470-e5634431-682b-456c-b135-4951f631771f.mp4

**Comment by briantho** [comment]
ok, i'm setting up smashbot on another computer to test. 

i just installed python and i'm getting this when trying to install libmelee




```


Collecting melee
  Using cached melee-0.37.0.zip (643 kB)
  Preparing metadata (setup.py) ... done
Collecting pyenet
  Using cached pyenet-1.3.14.tar.gz (786 kB)
  Preparing metadata (setup.py) ... done
Collecting py-ubjson
  Using cached py-ubjson-0.16.1.tar.gz (50 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy
  Using cached numpy-1.23.4-cp310-cp310-win_amd64.whl (14.6 MB)
Requirement already satisfied: packaging in c:\python310\lib\site-packages (from melee) (21.3)
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Requirement already satisfied: pywin32 in c:\python310\lib\site-packages (from melee) (304)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\python310\lib\site-packages (from packaging->melee) (3.0.9)
Collecting Cython<1,>=0
  Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
Using legacy 'setup.py install' for melee, since package 'wheel' is not installed.
Using legacy 'setup.py install' for py-ubjson, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pyenet, since package 'wheel' is not installed.
Installing collected packages: pyserial, py-ubjson, numpy, Cython, pyenet, melee
  Running setup.py install for py-ubjson ... done
  Running setup.py install for pyenet ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyenet did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running install
      C:\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      Compiling enet.pyx because it depends on C:\Python310\lib\site-packages\Cython\Includes\libc\string.pxd.
      [1/1] Cythonizing enet.pyx
      building 'enet' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyenet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip

```

how should i proceed?

**Comment by altf4** [comment]
Your video doesn't play, fyi. But your description sounds like you've got a delay. Does the screen say 2f in the bottom right? It shouldn't.

**Comment by altf4** [comment]
As for the Windows error, I dunno. The error tells you exactly what's wrong and how to fix it, so start there.

**Comment by briantho** [comment]
video plays fine under chrome and ms edge. my guess is because I had to encode it in h.265, so that it met the github file size requirement of under 10mb. if you can't get it to play still, i'll try a reencoding with a different codec. another option might be to just download the video, as it's made public and should be playable using any modern video player, such as vlc...

anyway, regarding delay there is none. i'm running this in 60fps, as seen by the video. the uploaded video is 30fps btw, but the emulator is running a full 60 while i was recording. this bug is constantly happening, regardless of if I am recording or not. 

as for the windows error on the other machine, I guess i'll start with installing Microsoft Visual C++ 14, as I just read the output log. 

let me know if you can get the video to play. thanks
in the meantime i'll try installing visual c++ on my other machine

**Comment by altf4** [comment]
Ahh, I can see the video in chrome. Weird it's not playing in FF. Meh.

Anyway, yea there's a delay. See how there's a little "2f" in the bottom right hand corner? That means all controller inputs are being delayed by two frames.

Follow item number 6 in the readme and see if that works.

**Comment by briantho** [comment]
ok, got it fixed. turned out i put the custom dolphin slippi code in the wrong place. i'd recommend updating the readme with the file location for windows mac and linux for slippi, so more people like me don't fork it up
something simple like this would do

```
windows location
C:\Users\<username>\AppData\Roaming\Slippi Launcher\playback\Sys\GameSettings

linux location

mac location


replace the GALE01r2.ini in this folder with this one
https://github.com/altf4/slippi-ssbm-asm/blob/libmelee/Output/Netplay/GALE01r2.ini 

```
to me that would be much more clear

**Comment by briantho** [comment]
hi, i just had one more quick question. is there any to make the gecko codes stick permanently, because it seems like the enabled codes reset each time i relaunch slippi. is this by design or something? it seems like every time i close smashbot, and restart it the selected codes are disabled and need to be reenabled. do you know any way to make gecko codes permanent?

**Comment by altf4** [comment]
That's due to a recent libmelee change that auto-sets the gecko codes for you. You can turn it off with an arg to the Console constructor.

https://github.com/altf4/libmelee/blob/master/melee/console.py#L117

**Comment by briantho** [comment]
> That's due to a recent libmelee change that auto-sets the gecko codes for you. You can turn it off with an arg to the Console constructor.
> 
> https://github.com/altf4/libmelee/blob/master/melee/console.py#L117

not quite sure i follow. if it auto sets the gecko codes, then why isn't "apply delay to all in-game screens" disabled. every time i relaunch smashbot "apply delay to all in-game screens" is set back as enabled, and I have to manually disable "apply delay to all in-game screens" for smashbot to work
