### ISSUE TITLE
How much of this is repurposable for libmelee?

### ISSUE THREAD

**Issue by Seremor108** [altf4/SmashBot#148]
SmashBot's code contains a lot of useful information related to:
- Projectiles/attacks/counters and defensive play
- Platform and stage data
- Fox frame data/recovery tech
Can this information relating to gameplay also be implemented in libmelee?

**Comment by altf4** [comment]
Is there platform and stage data? That part, maybe?

**Comment by Seremor108** [comment]
There are positions coded in for each platform on Battlefield and the other stages so that SmashBot knows where it's standing. If that sort of thing is already in libmelee then feel free to ignore this.
