### ISSUE TITLE
Fox gets stuck holding shield

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#22]
I don't know what causes it, but sometimes off the start of a match, Fox will shield and hold it permanently. You have to restart the emulator to get it to stop, just restarting the AI is not enough.

**Comment by altf4** [comment]
Should be fixed in 0897a256872ab9a9d05818800270ad37a3e7c0aa

**Comment by altf4** [comment]
Nope, still happens

**Comment by XeSquirmy** [comment]
Personally, I've never had this specific issue before, but it has happened to me when I've launched the game and I'm screwing around with my joystick. The cursor in game starts moving, and I have to restart the emulator again for it to stop. Unplugging my controller or doing the X+Y+Start method won't work either.

I think that this problem might be related to the trigger threshold shown in this picture: 
![smashbot](https://cloud.githubusercontent.com/assets/4617367/13755241/44e82292-e9e8-11e5-80df-402fb0445c6d.png)

Just throwing some of my own thoughts out.

**Comment by altf4** [comment]
I've seen that, too. I wonder if that's a symptom of an issue. Should the default settings be different than in GCPadNew.ini? If so, what should it be and why does it only cause a bug once in a while and not every time?

**Comment by XeSquirmy** [comment]
Honestly, I doubt that it's a symptom of the issue. For the meanwhile, I've put the trigger threshold to 99, and it can function fine like that. I'm not sure how much this issue pops up for you, but I think it's worth a shot.

**Comment by altf4** [comment]
Closed for v2.0
