### ISSUE TITLE
Wiggle out of hit stun in the air

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#29]
Right now the AI doesn't wiggle out of hitstun, so we're not able to act very quickly after getting hit. We should notice that we're in a damage state and wiggle out of the stun.

What buttons do we need to press here? All of them? Does the control stick matter? C Stick?

**Comment by r2dliu** [comment]
Any button will work, but optimally this is done with control stick on the first frame of tumble; does not work during hitstun. Wiggling the control stick puts the char in a neutral fall state versus any other input which forces a move.

**Comment by altf4** [comment]
Added in 706e56e94d3126fc95d1e2cbb9507f9fbf69b421
