### ISSUE TITLE
Implement DI

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#38]
Smash DI, perpendicular DI, random DI to throw off combos.

**Comment by altf4** [comment]
Added in 27a9406d42ce19d5f46dfea660aa104cf1c810fc

Still needs some more improvement or whatever, but it's food enough for now.

**Comment by geranim0** [comment]
I'm still hungry for more though

**Comment by altf4** [comment]
Take a peek in the Escape tactic. Feel free to add more logic in there for how Fox ought to DI certain hits in different situations!
