### ISSUE TITLE
Improve recovery tactic

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#39]
Right now, recovery is very rudimentary. Just FireFox and always at a diagonal angle. Let's make it mix up randomly and/or do the optimal thing always.

**Comment by Eppie** [comment]
I have an idea that might prove to be stronger than a purely random mix up. Have a look at [this analysis](https://daniel.lawrence.lu/programming/rps/) of Rock Paper Scissors algorithms. It's not _directly_ applicable, because our recovery options vs. our opponent's edge guarding options are disjoint sets, but I think with some tweaking, we could implement something that learns the opponent's preferred edge guarding options, and takes advantage appropriately. [Here](http://www.rpscontest.com/entry/437001) and [here](http://www.rpscontest.com/entry/541001) are two examples of implementations of these strategies. Notice that they have an ~80% winrate each, which is obviously superior to the ~50% you'd expect by just picking a move at random.

**Comment by altf4** [comment]
That's not a bad idea. I think that this is potentially applicable to more than just recovery actually. Basically any situation where we have to make a guess as to which options the opponent will cover. 

Keep in mind though, that many of these situations actually do have an optimal choice that beats everything. It's just that human-level play can't accomplish it. I haven't encountered anything in the game yet that is truly a RPS battle. Even recovery (against an enemy edgeguard) basically should never happen. (That's why SmashBot's recovery logic is so primitive: we shouldn't ever actually need to use it)

So if there is an optimal thing, SmashBot will always do that reliably every time. But who knows, I'm open to the idea of a RPS metagame. (especially in the Fox mirror, or maybe Falco too)

**Comment by Eppie** [comment]
Here's a potential refinement: 
We can think of this problem along the same lines as the [set cover problem](https://en.wikipedia.org/wiki/Set_cover_problem). We have some set of options **A** to choose from. The opponent has some set of options **B** to choose from. Each option in **B** covers some subset of the options in **A**. Now, **B** contains all options that are ever possible for the opponent, and similarly, **A** contains all of our possible options. However, we can reduce both sets by observing that given a character's current state / position, not all options are _currently_ possible. So, let's assume we've reduced both sets appropriately. In the best case, there will be some option in **A** that is covered by none of the options in **B**. Failing that, we can simply pick the option in **A** that is covered by the minimum number of options in **B**. A more effective alternative in this case might be to employ the type of algorithm I suggested previously, wherein we learn something about what our opponent is more or less likely to do, and choose appropriately.

And yes, I agree, this is applicable to more than just recovery. I am curious though, what makes you say this?

> Even recovery (against an enemy edgeguard) basically should never happen. 

Are you assuming that the bot is able to react to the opponent so well that it shouldn't ever get hit off stage?

**Comment by altf4** [comment]
Absolutely. SmashBot should never be off the stage in a position where it needs to recover. (Excepting instances where it deliberately runs off stage to shine and such) The recovery logic is just there because it's not yet perfect and recovering makes for more interesting matches until we get there.

**Comment by altf4** [comment]
There's been a number of recovery improvements lately, so I'm going to close this issue as it's overly broad. If there are any specific problems that come up, let's make new issues for those.
