### ISSUE TITLE
Auto setup not working

### ISSUE THREAD

**Issue by geranim0** [altf4/SmashBot#42]
ERROR: $XDG_DATA_HOME was empty and so was $HOME/.dolphin-emu.Make sure to install Dolphin first and try again.

**Comment by altf4** [comment]
Blah, apparently nobody obeys the XDG standard. I added some new clauses that should handle it. 

You're on Debian right? Is your dolphin folder in $HOME/.local/share/dolphin-emu ?

Try commit: 59f433f780d452d3f6f563a3ed7986164002476e

**Comment by geranim0** [comment]
yes and yes

**Comment by altf4** [comment]
@geranim0  Does the latest version work for you? If it does, I'll close this issue.

**Comment by altf4** [comment]
Gonna close this issue again. Go ahead and reopen it if you're still having trouble here.
