### ISSUE TITLE
Latency on controller input?

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#51]
Every once in a while, a button press won't have its intended effect right away, it will take a whole frame in extra latency. For instance, look at the following log:

```
850	KillOpponent	Bait	ShowOff	Multishine	20.848515	73.08757	36.884499	0.0001	7	24	7	2	1	0	4	4	89	0	"INFO: Button press: B
INFO: Tilt analog: MAIN to 0.500000, 0.000000"
851	KillOpponent	Bait	ShowOff	Multishine	19.575184	68.302864	36.884499	2.1001	7	25	8	0	1	1	4	4	89	0	"INFO: Blank controller input
852	KillOpponent	Bait	ShowOff	Nothing	20.673336	63.4725	36.884499	2.1001	7	365	9	1	1	1	4	4	89	0	"INFO: Blank controller input
```

On frame 850, SmashBot presses down-B. Frame 851, nothing happens and Fox begins to jump (he was in the knee bend animation). Then on Frame 852, the shine happens. 

I suspect that there is some variable latency with our controller input subsystem...

**Comment by geranim0** [comment]
I don't know if this is related, but I recently tried to TAS and had the same problem. Sometimes the input would occur 1 frame later.

**Comment by altf4** [comment]
I'm going to add some timing instrumentation to get a better handle on this bug. I suspect that a lot of the other random little bugs I see might be caused by this. Additionally, I notice a lot of late frame warnings as the game goes on. That also may or may not be related.

**Comment by altf4** [comment]
Looks like the delays aren't random at all. They seem come in waves where EVERY input is delayed by 1 frame. I'm starting to suspect that this is an emulator issue, but I'm not positive.

**Comment by geranim0** [comment]
it was the same for me as well

**Comment by altf4** [comment]
Confirmed as a dolphin bug. I'm closing this.

https://bugs.dolphin-emu.org/issues/9016

**Comment by geranim0** [comment]
You probably know about this by now but you shoul read this

https://www.reddit.com/r/smashbros/comments/4pcfbv/melee_on_console_how_much_input_lag_is_there_and/

and the comment of dansalvato in the comment section

**Comment by altf4** [comment]
Yea, I actually helped Dan confirm that issue and verify his gecko code solves it. The latency fix gecko code included in SmashBot is a fix for exactly that problem.

Make sure to apply that before trying to run SmashBot, btw.
