### ISSUE TITLE
Attempting to use Memory Watching Code

### ISSUE THREAD

**Issue by Yittik13** [altf4/SmashBot#56]
I've been trying to use some of the Memory Watch code. I have it working for the most part but it only finds two of the addresses (the ones for player 1 and 2 air speed, 00453130 E4 and 00453FC0 E4). I'm running the code under Mac OS X and using the Locations.txt file provided here. This could possibly be the problem, but I'm not sure. Any help would be appreciated!

**Comment by vladfi1** [comment]
I personally had a lot of trouble using SmashBot on OSX, so I switched to using python for the memory watcher/named pipe interface. Look at https://github.com/spxtr/p3/blob/master/p3/state_manager.py or https://github.com/vladfi1/phillip/blob/master/state_manager.py for examples.

**Comment by Yittik13** [comment]
Cool, thanks! I think I'll try running it under a linux environment and see if anything changes.

**Comment by altf4** [comment]
I wouldn't mind supporting OSX honestly. I just am not a Mac person and don't have any way to test it. So if you figure this out, I'd love to push a fix or instructions or whatever.
 
That said, those memory addresses in Locations.txt are static pointers in Melee's code. It shouldn't matter what OS you're on. It MIGHT matter, come to think of it, what version of Melee you have. I'm pretty sure mine is 1.02, but I will verify that tonight. Are you using 1.00 by chance? That would definitely cause the problem you seem to be having.

(Also in case you were wondering, this project is still very live. I just had a different project I was doing last month. I'm back to doing SmashBot work now)

**Comment by Yittik13** [comment]
I'll definitely let you know if I figure anything out. 

I'll be testing it on Linux soon and see if that changed anything. I am in fact using 1.00, I'll have to update Melee then, thanks for that info!

Great, it will be interesting seeing where this project goes.

**Comment by Yittik13** [comment]
Updated melee to version 1.02, and the code seems to be working.

**Comment by altf4** [comment]
Perfect! I'll update the Readme to let others know to use Melee 1.02.

**Comment by altf4** [comment]
Added in c6cef7d
