### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by Eppie** [altf4/SmashBot#66]
This wouldn't exactly be a high priority, but here's what I'm thinking:
Sure, the bot can do some amazing tech chases to rack up damage, and can avoid getting hit with its great power-shielding. We've seen that in the YouTube video. But, after the first couple of minutes of watching it play, it gets kind of boring and repetitive. I think it would be great if the bot had some style that made it an entertaining player to watch. It's already got at least one example of what I'm talking about, which is the multi-shining that is showed off in the video after it kills Marth.

Obviously there are more opportunities for style against lower level players, because it's less likely that something stylish but not optimal will get punished. Maybe the bot can have difficulty levels? At the highest difficulty it plays as optimally as possible, and at lower difficulties, it plays increasingly risky but also increasingly stylishly. Alternatively, maybe it could automatically adjust. For example, it could begin the match by throwing out some slightly risky move, and then adjusting its play-style in response to the opponent's punishment (or lack thereof) of that move.

As I said, this idea would be something to do _after_ working out whatever bugs may still be present, and adding in whatever more important features that haven't been done yet.

**Comment by altf4** [comment]
People have been asking this sort of thing consistently, which is "can we make SmashBot fun to play against?"

My reaction is that "Fun to play against" isn't SmashBot's goal, and it's not even clear what that means. Does it mean that it should let you win sometimes? (Some people don't find being JV 5-stocked fun) Or maybe it means that it should kill you in different ways? I don't know, and it seems to mean different things to different people. My first suggestion is to rephrase the goal in terms of something more concretely achievable than "fun to play against". (Is it supposed to be a good practice partner?)

It would actually be simple enough to make an "Aggro" strategy to replace Bait. It would throw out hitboxes at the opponent even if it's unsafe, sort of like how a human plays. It would still have frame-perfect reactions, but perhaps seem more human-like in playstyle.

**Comment by altf4** [comment]
And yes, it would be simple to swap back and forth between these strategies mid-game. Maybe based on gamestate (change strategy based on how many stocks SmashBot has left) or even user input. (Change strategy when a user presses a button to switch modes)

**Comment by altf4** [comment]
In any case, I do like the idea. There's just a lot of things on the project roadmap. Perhaps I'll add a project roadmap graphic to the Readme. Solidifying the Marth FD matchup, adding support for other characters, support for all the neutral stages, making SmashBot run on console, machine learning, so much.

**Comment by vladfi1** [comment]
@Eppie I'm trying to make a human-like smash bot using machine learning over at github.com/vladfi1/phillip. It isn't quite good enough yet to be fun to play against though.

**Comment by altf4** [comment]
So, after another evening of playtesting with some smashers in my area, I think the general consensus was that the tech chase combo is irritating to play against. I'm pretty convinced that I can make it into a zero-death combo... but is it worth it if people won't want to play against SmashBot? I stand by my assertion that the goal is not to be fun, (it is to win) but at the same time it's not doing any favor to itself by not getting played. 

Maybe there's another option that's just as optimal but not as annoying to play against. I think the reason that people dislike the tech chase combo is that all options are removed from you, and it takes a long time to finish. It's a really slow death that can take almost a minute per stock. Maybe we'd be better off just waveshining the opponent off the edge and then edgeguarding them. I dunno.

**Comment by geranim0** [comment]
just implement a config file where plebs can disable tech chase. You
shouldnt try to please the peasants

2016-06-22 14:32 GMT-04:00 AltF4 <notifications@github.com>:

**Comment by Eppie** [comment]
> I stand by my assertion that the goal is not to be fun, (it is to win)

Agreed, "winning" should definitely be the goal, not "fun" or "training" / "practice". Those more objective goals can come later, if at all.

**Comment by altf4** [comment]
I think I may make the default build have an "Aggro" strategy that it uses in the first two stocks of the game, where it sort of YOLOs out a bunch. It would be "fun" but probably suboptimal. Then if you manage to take two stocks, you have to play against the Bait strategy where it plays optimally.

**Comment by altf4** [comment]
Closed for v2.0
