### ISSUE TITLE
Air tumbling causes shine to sometimes miss

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#67]
Tumbling air animations cause the "center" of a character to be wildly unrepresentative of where they actually are. The bottom of the character is always considered to be where their feet are, which causes SmashBot to miss some aerial shines, like this one:

![selection_001](https://cloud.githubusercontent.com/assets/609563/16328756/13e35208-3992-11e6-8604-779c062ef72a.png)

You can see in that image that if Marth were standing upright, the shine would have hit. But since he's leaning backward, it missed. I've seen this issue happen frequently and I'm not sure of the best way to handle it. I **really** don't want to go down a kludgey path of hardcoding character model offsets for each animation that causes a large deviation from standing.

**Comment by altf4** [comment]
It should be primarily a vertical offset problem, I think. So perhaps we can just require a closer vertical overlap before shining if the enemy is in a known tumbling state (there's only a few). That sounds like a reasonable compromise.

**Comment by Eppie** [comment]
How hard do you think it would be to hook the game's "collision detection" function? If you could do that, then you could just use it to answer the question of "Will attack X connect with character Y given current state Z?" without worrying about any of the internals of character positions or model sizes or any of that stuff.

**Comment by altf4** [comment]
It would be hard. :) There's a few reasons why:

1) MemoryWatcher in dolphin is really not setup for that kind of thing. We have to provide a stable memory region for it to inspect, and then it sends us a new value any time it changes. Hooking into a function would need some totally new logic on both dolphin's part and SmashBot's.

2) Detecting whether your attack will land is actually dependent on your opponent's input. Hit detection is processed near the end of the game engine's routine. So for instance, suppose we are definitely in range for shine, but near the edge of range. SmashBot presses down-B at the same time that the opponent dashes away. Both user's input is processed and the new dashing state from the opponent puts it out of range of the shine, which then misses.

There's no way we could have anticipated the opponent's dash, since it hasn't happened yet. And even calling the in-game collision detection wouldn't have helped since it would have told us "yes, we're in range". The only good solution is to be a little conservative and get close enough where we're pretty sure the attack will land no matter what their next state will be. And if we're doing that, then there's no point in having the in-game collision detection's accuracy.

**Comment by altf4** [comment]
Closed for v2.0
