### ISSUE TITLE
Punish with aerial attacks

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#68]
I've avoided aerial attacks up to this point because staying on the ground is simpler in terms of logic and options, but as I'm readying for support of other non-FD stages it's becoming clearer that aerial attacks are going to likely be the best option in many cases. (combos with platforms)

A simple algorithm that looks at how much stun the opponent has, and where they will end up at the end of the stun should be enough to plug into a calculation of what attack we can put at that place in time. Very similar to how the tech chase combo logic works.

It will be a greedy algorithm, and so may fall short of "optimal" play. But who cares. DI and smash DI is too hard to account for to do the optimal thing here. This way is also cooler because it will allow SmashBot to discover combos all on its own as it does the math to find what's possible. It may also "feel" improvisational, since SmashBot is making up the combo on the fly with each hit.

**Comment by Eppie** [comment]
Let me know when the greedy algorithm is implemented. I'll take a look at
it, maybe I will be able to improve it using random restarts or stimulated
annealing or something like that.

**Comment by altf4** [comment]
Closed for v2.0
