### ISSUE TITLE
Build is failing under ubuntu Mate.

### ISSUE THREAD

**Issue by briantho** [altf4/SmashBot#70]
Hi, I just cloned your git, and am trying to build under ubuntu MATE 16.04, however when i get to the step "make" under terminal I get 

brian@brian-ubuntu:~/Desktop/Smashbot (7-2-16)/SmashBot$ make
g++ -g -c -Wall -std=gnu++11 Goals/*.cpp
/bin/sh: 1: g++: not found
Makefile:21: recipe for target 'goals' failed
make: *** [goals] Error 127

I have no clue what i"m doing wrong, so if you could please help me, i would appreciate it greatly. This is a new ubuntu install, and I've followed you guide perfectly up to where it says to build by using "make"

**Comment by XeSquirmy** [comment]
Make sure you have g++ installed
`sudo apt install g++`

**Comment by briantho** [comment]
ok, that fixed it. Should put that as one of the dependencies, for new users. Also took me a while to figure out where to put GCPadNew.ini should really be documented better...
