### ISSUE TITLE
GCPadNew.ini is set for Player 1 Not 2

### ISSUE THREAD

**Issue by briantho** [altf4/SmashBot#71]
I couldn't get smashbot to work till I edited GCPadNew.ini and changed [GCPad1] to [GCPad2]
Also, I think it is a good idea to put what directory GCPadNew.ini goes, as it took me a while to figure it out. This should be updated in the readme for new users like me. Thanks.

**Comment by altf4** [comment]
Maybe you're right, I dunno. Honestly, you shouldn't have to configure the controller settings like that anyway. It should come default with dolphin. Maybe I'll make a pull request with them to include it in future builds. 

The reason I didn't want to get into specifics of controller setups is that it's going to be different on every OS.

**Comment by briantho** [comment]
Isn't the purpose of the GCPadNew.ini to set up the virtual controller for Smashbot? So what do you mean by default? Also, after I copied the GCPad File to the right directory, I went to go launch dolphin, and configured my gamecube controller, but found that for player 2's controller (smashbot) I couldn't select the pipe, or configure any of the bindings. Took me a bit to figure out to edit the GCpad file, and then I noticed that [GCPad1], meant player 1 and it should be player 2, so I changed it tried DOlphin again, and it worked automatically. When I went to the controller setup for player 2, everything was set up automatically

**Comment by altf4** [comment]
I changed the GCPad1 to GCPad2 in 2bb518db94aca29dbf1273d3f7ddf028bf2ba212
