### ISSUE TITLE
Figure out FoD platform movement

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#72]
I hear they move randomly. This will be really hard to support if that's true...

**Comment by ChimeraReyat** [comment]
Wouldn't it be possible to read the platform locations in memory, if the pointers to their locations can be deduced? And possibly calculate their velocity based on previous and current frames?

If FOD's platform velocity is predictable, i.e. how fast a platform's moving when it's going to stop at a designated position, that could give Smashbot an idea of where the platforms will be.

This is of course assuming FOD's platforms both decelerate predictably and have exact positions they stop at.

**Comment by altf4** [comment]
That'll help, except for long-term planning purposes. Maybe it's good enough in 99% of the cases. Though I still don't know where the platform position / speeds are stored.

**Comment by eaglgenes101** [comment]
Smashbot occasionally hiccups for one frame to give it a fighting chance against itself, so it's already beatable by actual TAS opponents. I think that just using short-term planning to decide how to act with platforms should be enough, and that the 1% where this is suboptimal is not worth sweating about. 

(And besides, wasn't this project all about abusing computer perfection and reaction time to not need cognitive capability such as long-term planning?)

**Comment by altf4** [comment]
...what?

**Comment by altf4** [comment]
anyway, this is really more of a libmelee issue, so I'm moving it to there.
