### ISSUE TITLE
Better graphics / images

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#73]
The sample animated GIFs and images on the Readme are okay, but could be better. I don't exactly have the artistic inclination, however, to do much better. Anyone else wanna take a stab?

**Comment by Eppie** [comment]
If you can make some videos, I can convert them to high quality gifs.

**Comment by Eppie** [comment]
Btw, if you still have the original videos used to produce the gifs you have right now, I could probably at least create higher-quality gifs out of them.

**Comment by altf4** [comment]
I don't think I have the original videos for those GIFs anymore. But I'll try to get more videos made. Believe me, I'm trying. I'm just super busy at the moment until DEF CON is over :)

**Comment by altf4** [comment]
Closed for v2.0
