### ISSUE TITLE
Configuration on OSX

### ISSUE THREAD

**Issue by ThiBen** [altf4/SmashBot#75]
I cannot get the SmashBot working on OSX, I can start the game and select my own character, but the cpu will never control anything. I copied the GCPadNew.ini in the folder /Users/[Me]/Library/Application\ Support/Dolphin/Config, and removed the previous one because it was of no use for me (I am using the wiiU adapter). I also modified the [GCPad1] into [GCPad2] as suggested in a other bug report.
In the controler config, I can then select pipe/0/SmashBot, which has a automatic configuration and it seems to correspond to the right one. But when I run smashbot and then Dolphin and Melee, the script writes in the terminal the following message: 
`home_path: /Users/[Me]
osx_config_path: /Users/[Me]/Library/Application Support/Dolphin/
home_path: /Users/[Me]
osx_config_path: /Users/[Me]/Library/Application Support/Dolphin/
WARNING: FRAME MISSED
home_path: /Users/[Me]
osx_config_path: /Users/[Me]/Library/Application Support/Dolphin/
DEBUG: Waiting for Dolphin...
DEBUG: Off to the races!
`

But then when I try selecting a character, the second player just doesnt move at all and does not select fox.
I am using the version on the project which is on the branch osx, and activated all the gecko codes as indicated. I also tried the master branch, but same problem.

Does anyone know how to configure the app to make it work on OSX?

**Comment by altf4** [comment]
The osx branch was only there for debugging and shouldn't be what you actually use. Just use master.

What does your controller settings window look like, for Player 2? It should look something like this:

![gamecube controller configuration_009](https://cloud.githubusercontent.com/assets/609563/16710497/7ac865ee-45e5-11e6-966a-a72ebb329e74.png)

Note that all the buttons are filled out and stuff.

When SmashBot says "off to the races" that means it has received input from dolphin and is TRYING to press buttons. There must be something off in your controller settings.

**Comment by naltieri** [comment]
I'm having an issue getting it working as well. I am using the master branch. Though I'm not getting "Off to the races". 

Instead it gets stuck line 130 in smashbot.cpp. More specifically it hangs on line 44 of MemoryWatchter: 

recvfrom(m_file, buf, sizeof(buf), 0, &remaddr, &addr_len);

I also can't seem get it to configure the controller setting as in your figure.

**Comment by altf4** [comment]
About the controller settings... that gets kind of complicated and doesn't really have anything to do with SmashBot. It's just how Dolphin does it, and it's not ideal. I made a bug report with them that ought to improve things:

https://bugs.dolphin-emu.org/issues/9688

It's really beyond the scope of what I can do to make an exhaustive guide for how to set up controller settings for Dolphin. But I understand the frustration about how that's not a very good answer.

As for blocking on MemoryWatcher, that means that SmashBot is waiting for Dolphin to connect over the MemoryWatcher domain socket file but it isn't working. Are you sure dolphin is running? If you're sure dolphin is running normally, try looking inside Dolphin's config directory here:

/Users/[your name]/Library/Application Support/Dolphin/MemoryWatcher/

You should find two files: Locations.txt and MemoryWatcher. If they're not both there (and you have run both SmashBot and Dolphin) then something's gone wrong.

**Comment by naltieri** [comment]
So in regards to the socket issue: 
I have located both of the aforementioned files, but still no luck. [It still never gets past the first recvfrom call.]

I've heard that sockets work differently on OSX and Linux (but that's really the extent of my knowledge). Do you think it could be related to this?

**Comment by vladfi1** [comment]
I encountered similar problems on OSX. They went away when I switched from
C++ to python.
On Jul 11, 2016 1:01 PM, "naltieri" <notifications@github.com> wrote:

So in regards to the socket issue:
I have located both of the aforementioned files, but still no luck. [It
still never gets past the first recvfrom call.]

I've heard that sockets work differently on OSX and Linux (but that's
really the extent of my knowledge). Do you think it could be related to
this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/altf4/SmashBot/issues/75#issuecomment-231797153>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAqNUE6Yl1tpCwB3eesO1oUMIokFDAunks5qUnbmgaJpZM4JIqiC>
.

**Comment by naltieri** [comment]
That's awesome! Can you expand more on what you mean by "They went away when I switched from
C++ to python."?

**Comment by vladfi1** [comment]
I switched from using a C++ bot based on altf4's to a python one based on
https://github.com/spxtr/p3 (my bot is at github.com/vladfi1/phillip). This
won't help you run altf4's bot though, unless you can convince him to
rewrite everything in python.

**Comment by naltieri** [comment]
Ah I see! I'll definitely look into that! Thanks a lot for the help :)

**Comment by altf4** [comment]
@naltieri Dolphin 4.0 will definitely not work. Says so in the readme. Download 5.0 and try again.

**Comment by naltieri** [comment]
Ah! Thanks! I originally pulled the code a long time ago (pre-5.0) for linux and forgot to re-read the readme. Sorry for the bonehead move.

**Comment by ThiBen** [comment]
I finally got the SmashBot working in my computer, but I noticed a bug. I also play other games which usually work fine, but after lauching SmashBot, Dolphin crashes launching the game, with the following error:
Unknown Pointer 0x10000144 PC 0x8030d0f4 LR 0x8030d0f4.

I figured out that it is due to the Location.txt file which is copied by SmashBot inside the MemoryWatcher folder of Dolphin config, so if I remove it everytime after using SmashBot it works. But I think this file should be removed from the folder by Smashbot itself

**Comment by spxtr** [comment]
It might be worth a patch to dolphin to make it do a bounds check before dereferencing pointers.

**Comment by altf4** [comment]
Yea, that's a dolphin bug. What's happening is that Dolphin is trying to look up the Melee memory regions on a non-melee game, which then crashes. Feel free to log a bug report with Dolphin about it.  

In the meantime, I'm going to close this as it looks like SmashBot is working on OSX. Sorry for the headaches along the way.
