### ISSUE TITLE
Melee Research: Gravity constant for each character

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#76]
In order to support each character, SmashBot needs to know some info on how the game physics works. 

Each character has a gravity constant that defines how quickly they accelerate downward under normal circumstances. Fox has a gravity constant of .23, Marth is .085. This means that when falling, the character will move downwards G faster than last frame, where G is the character's gravity constant. 

Can someone do some research and figure out what the gravity constants of every character is? You can use SmashBot to do this. Just run with the --debug flag and look at the CSV file it gives you. Jump and then fall with your character. Then do some subtraction to discover the gravity constant. 

Thanks!

**Comment by spxtr** [comment]
Can you use the values on [the sheet](https://docs.google.com/spreadsheets/d/1JX2w-r2fuvWuNgGb6D3Cs4wHQKLFegZe2jhbBuIhCG8/edit#gid=21)? I see gravity, terminal velocity, and fast fall terminal velocity.

**Comment by altf4** [comment]
Yea, that will definitely work. Sweet, I haven't seen that page yet. Thanks!

**Comment by Eppie** [comment]
Gah, I sent that sheet to you in an email a month ago! :frowning:

**Comment by spxtr** [comment]
I had been using that sheet for a long time before I realized that there were more sections at the bottom :)

**Comment by altf4** [comment]
Yea, that's basically what happened to me, too. Some useful information is there. But not everything I need. Also, some of that info on the sheet is wrong. So, I'll have to look into it a bit.

**Comment by vladfi1** [comment]
They shifted all the addresses for some reason: "Since May 28, 2016, we are now using the in-game offsets".
