### ISSUE TITLE
Horizontal movement equilibrium speed

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#78]
In order to support each character, SmashBot needs to know some info on how the game physics works. I need some help in figuring it out!

Each character in Melee has a horizontal air "equilibrium" speed. It's the horizontal speed limit of each character, basically. If you're moving less than this speed and holing over, you will accelerate up to this speed. If you're moving more than this speed and holding over, you will decelerate down to this speed. 

SmashBot needs to know what this equilibrium is for every character. You can use SmashBot to do this, run with the --debug flag set and look at the CSV file it gives you with character positions.

Thanks!

**Comment by altf4** [comment]
For example, Marth's horizontal equilibrium speed is 0.88875 and Fox's is 0.819625.

**Comment by spxtr** [comment]
The sheet has max H air speed but it seems a little imprecise.

**Comment by altf4** [comment]
Yea, I saw that. I think this is a case where we need to improve on it.

**Comment by altf4** [comment]
Closed for v2.0
