### ISSUE TITLE
Double jump height

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#82]
How high does each character double-jump? 

Use SmashBot to determine this, run with the --debug flag and inspect the CSV file it gives you. 

Examples: Marth jumps 25.187989, Fox jumps 40.203998.

(Note: Yes, technically this could be derived at runtime, but we use this number often enough that it's worth a shortcut figure)

**Comment by dantarion** [comment]
I am going to be publishing something related to figuring out numbers like this straight from character attributes. That way you will be able to predict "how high will X character be after Y frames of his double jump".

**Comment by altf4** [comment]
Well, I already have this:

https://github.com/altf4/SmashBot/blob/master/Util/GameState.cpp#L1609

This issue was just to have a shortcut maximum double jump height constant for each character, so we don't have to derive it at runtime every use. It happens all the time, so we could probably save a lot of cycles this way.

**Comment by altf4** [comment]
Closed for v2.0
