### ISSUE TITLE
Having issues setting up SmashBot

### ISSUE THREAD

**Issue by primetoxinz** [altf4/SmashBot#88]
I am attempting to use SmashBot to help with a school project, but am having issues. If you are available to discuss this in a better location like irc or discord that would be great, or here is fine if that's ok. Just need some help, thanks :)

**Comment by altf4** [comment]
If you're having a specific technical problem, post about it here. Others may be having the same issue, so let's work through that publicly.

**Comment by primetoxinz** [comment]
I do not know what the issue is per se, just know that the bot is not working.
I ran `make` on this repo, checked cheats and netplay community settings ( and even compiled a fix for gecko code in the current dolphin), setup the GCPadNew.ini same as in the repo and setup 2 players, with player 2 using the smashbot pipe. I launch the smashbot, then smash and the bot is still no present.
Maybe if you can add some stdout logging so it can be confirmed running it would help with finding if ther e is a real issue

**Comment by altf4** [comment]
Does SmashBot give you any command-line output when you run it?

(There should be a message like "off to the races", which admittedly is not a great message, that indicates that it has connected with Dolphin over MemoryWatcher and is now trying to press buttons)

Are you using Dolphin 5.0?

**Comment by primetoxinz** [comment]
the only output smashbot made was the first time it launched to make the memorywatcher, after that it has said nothing.

yes I am using 5.0

**Comment by altf4** [comment]
It probably should be ~/.local/share/dolphin-emu/MemoryWatcher/

What exact OS are you in?

**Comment by primetoxinz** [comment]
archlinux

**Comment by primetoxinz** [comment]
btw, running dolphin first corrected the config path, so that was not a real issue

**Comment by altf4** [comment]
SmashBot talks to Dolphin over Unix domain sockets for MemoryWatcher. That's what the recv will be. SmashBot is trying to receive updates from Dolphin about what the gamestate is, but not receiving any. 

- Are you running Melee v1.02 NTSC? (other versions will not work)

- Is there a Locations.txt file located in:

~/.local/share/dolphin-emu/MemoryWatcher/Locations.txt

There should also be a:

~/.local/share/dolphin-emu/MemoryWatcher/MemoryWatcher

**Comment by primetoxinz** [comment]
it is v1.02, but Idk what NTSC mean
there is a Locations.txt and MemoryWatcher socket

**Comment by altf4** [comment]
IE: Not the European or Japanese version. (Use the USA version)

**Comment by primetoxinz** [comment]
how can I verify I am on that version?

**Comment by altf4** [comment]
Right click the Melee icon in Dolphin's main menu -> Info Tab

There will be a button halfway down that says Compute. Hit that and see what the MD5 Checksum shows. It should be:

0e63d4223b01d9aba596259dc155a174

**Comment by primetoxinz** [comment]
yep, 0e63d4223b01d9aba596259dc155a174 is definitely the same hash

**Comment by altf4** [comment]
Make sure your controller settings are correct. Your controller setup should look something like this:  

https://cloud.githubusercontent.com/assets/14268883/18417216/9da0e120-7864-11e6-819a-2bc0afe9e45b.png

Also, make sure that window focus is on Dolphin during gameplay and not anywhere else. (This is a Dolphin thing, and I think is on purpose) Others have made this mistake. Just click on Dolphin and don't click outside it.

**Comment by spxtr** [comment]
Why does dolphin need focus? I thought the point of "Background Input" was that it doesn't.

**Comment by primetoxinz** [comment]
As you can see [https://imgur.com/a/UkC4K](here) all of the settings are correct.
I added extra logging to SmashBot for testing like so
`
logger->Log(INFO,"1");
recvfrom(m_file, buf, sizeof(buf), 0, &remaddr, &addr_len);
logger->Log(INFO,"2");
`
as you can see in the terminal with smashbot "1" prints "2" does not, so recvfrom just hangs forever

**Comment by altf4** [comment]
@spxtr You CAN enable background input, but it's not default. (I don't know why) SmashBot should work fine with background input enabled, though.

@primetoxinz It seems like SmashBot is waiting for input from Dolphin's MemoryWatcher, and not receiving anything... Maybe Arch puts Dolphin's settings directories in weird places? What is the contents of:

~/.local/share/dolphin-emu/

There should be a bunch of folders like:

Dump          GC    Logs  MemoryWatcher  ScreenShots  StateSaves  Wii
GameSettings  Load  Maps  Pipes          Shaders      Themes

**Comment by vladfi1** [comment]
For my bot I've been using a custom dolphin directory (the `--user` option). Might be worth adding this to your bot too so people can have a custom config just for the bot.

**Comment by altf4** [comment]
@vladfi1 A custom dolphin directory? How does that work? Dolphin needs to read the Locations.txt file and such, so we still need to auto-determine where that is. (Do you mean an option to manually override where SmashBot thinks Dolphin's settings folder is? That could work, but it's still complicated. SOME distros differentiate between config and settings, some don''t.)

**Comment by vladfi1** [comment]
Yeah I mean explicitly telling the bot which directory contains the MemoryWatcher and Pipes dirs. I think when setting --user explicitly dolphin uses that directory for both settings and config (which is how I have my bot automatically configure dolphin).

**Comment by spxtr** [comment]
On my machine it's in `~/.dolphin-emu`. See https://github.com/spxtr/p3/blob/master/p3/p3.py#L13

**Comment by primetoxinz** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/4721642/19017857/8f2c978c-8819-11e6-901c-62811f279208.png)

**Comment by altf4** [comment]
Do you also have those same folders (Dump, GameSettings, GC, etc..) under ~/.dolphin-emu/ ?

**Comment by primetoxinz** [comment]
~/.dolphin-emu does not existing
