### ISSUE TITLE
Perfect optimal play may be asymetrical

### ISSUE THREAD

**Issue by deveyus** [altf4/SmashBot#89]
I recently saw the Defcon presentation on youtube in which you discussed what perfect play would look like, and I suspect that you may be incorrect about projectiles being an always suboptimal option.  Projectiles such as falco's laser may be able to be used to create gambit situations that force a fox to either take a laser or an attack due to the lag of execution on in-place shines and the rate some attacks come out at, meaning that there's never enough lean time for a defending fox to guarantee an escape from all possible attacks.  This may exist for a number of characters, including peach via slow, arching trajectories (though they may be able to be moved out of) and Samus (through Super Wavedashes, and multiple projectiles in the air.)  Simply food for thought.

**Comment by altf4** [comment]
For other character matchups, I suspect that Fox just plain wins all of them. Maybe there's something that I'm not considering and it turns out that Yoshi parries are super broken at the top level, but I doubt it.
