### ISSUE TITLE
configparser.NoSectionError: No section: 'Core'

### ISSUE THREAD

**Issue by rosshadden** [altf4/SmashBot#93]
I get the following stacktrace when attempting to run `smashbot.py`:

```
Traceback (most recent call last):
  File "./smashbot.py", line 54, in <module>
    opponent_type=opponent_type, logger=log)
  File "/usr/lib/python3.6/site-packages/melee/dolphin.py", line 41, in __init__
    self.setup_controller(ai_port)
  File "/usr/lib/python3.6/site-packages/melee/dolphin.py", line 99, in setup_controller
    config.set("Core", 'SIDevice'+str(port-1), controllertype.value)
  File "/usr/lib/python3.6/configparser.py", line 1193, in set
    super().set(section, option, value)
  File "/usr/lib/python3.6/configparser.py", line 901, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Core'
```

**Comment by altf4** [comment]
What platform are you on? libmelee is complaining about a missing section from a dolphin config file when trying to setup a controller.

**Comment by rosshadden** [comment]
Arch Linux, with the dolphin compiled from your fork.

**Comment by altf4** [comment]
Does arch store app config files somewhere other than ~/.config/APP/ ?  (Is that a debian-ism?)

In any case. that's where Ubuntu does, and I suspect why libmelee is crashing. It can't find the main dolphin config file. 

That said, there ought to be a better error message an an opaque stack trace. We should catch it and complain that it can't find the config file / something is wrong with it.

**Comment by rosshadden** [comment]
Arch does store config files in ~/.config, though it's worth noting that it's a best practice to use `$XDG_CONFIG_HOME` and other similar XDG vars.

Dolphin's configs are stored in `~/.dolphin-emu/Config` by default, however I'm not sure how that works because I have four or five different dolphins that I use at this point, haha.

**Comment by altf4** [comment]
I recall doing some research on app config directories a while back and seeing $XDG_CONFIG_HOME. Apparently it's a "standard" but Ubuntu doesn't use it. $XDG_CONFIG_HOME is just blank on my machine. Does arch actually use it? I could add a line to check if the var is set I guess.

**Comment by rosshadden** [comment]
Interesting.  I would think if any distro followed that convention it'd be Ubuntu.  My memory says Mint does, but could be wrong.  Also no, Arch doesn't do anything like that for you.  I have them set manually because I've used a lot of tools that look in those `XDG_` directories :D.

**Comment by altf4** [comment]
I'm closing for now since this is quite old. But if Arch is still not working, we can reopen and fix it

**Comment by adriendod** [comment]
Hi, got the same error but on mac os... Any work around? I have no idea where are supposed to be the config files

**Comment by magicc11** [comment]
Got the Same error on windows. Any wayout ?

**Comment by altf4** [comment]
Did you try running the emulator once already like above?
